name: nfc_reader
description: A nfc reader plugin for Android. Currently it only supports reading NDEF formatted tags.
version: 1.0.0
author: Ahmed Mirza <ahmed.mirza994>
homepage: https://github.com/ahmedmirza994/Nfc-reader

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: com.trigsoft.nfc_reader
    pluginClass: NfcReaderPlugin

